logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http]
  address = ":80"

[acme]
  storage = "traefik/acme/account"
  email = "hello@ellcrys.co"
  entryPoint = "https"
  onDemand = true
  OnHostRule = true
  acmeLogging = true

[[acme.domains]]
   main = "ellcrys.io"

[web]
  address = ":8070"

[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik"

