// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Tx
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Tx struct {
	Status int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Id     string   `protobuf:"bytes,2,opt,name=Id" json:"Id,omitempty"`
	Name   string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Params []string `protobuf:"bytes,4,rep,name=params" json:"params,omitempty"`
	Body   []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto1.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tx) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Tx) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tx) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tx) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Tx) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto1.RegisterType((*Tx)(nil), "proto.Tx")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stub service

type StubClient interface {
	Invoke(ctx context.Context, in *Tx, opts ...grpc.CallOption) (*Tx, error)
}

type stubClient struct {
	cc *grpc.ClientConn
}

func NewStubClient(cc *grpc.ClientConn) StubClient {
	return &stubClient{cc}
}

func (c *stubClient) Invoke(ctx context.Context, in *Tx, opts ...grpc.CallOption) (*Tx, error) {
	out := new(Tx)
	err := grpc.Invoke(ctx, "/proto.Stub/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stub service

type StubServer interface {
	Invoke(context.Context, *Tx) (*Tx, error)
}

func RegisterStubServer(s *grpc.Server, srv StubServer) {
	s.RegisterService(&_Stub_serviceDesc, srv)
}

func _Stub_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StubServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Stub/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StubServer).Invoke(ctx, req.(*Tx))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Stub",
	HandlerType: (*StubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Stub_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x39, 0x5c, 0x4c,
	0x21, 0x15, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x50, 0x9e, 0x10, 0x1f, 0x17, 0x93, 0x67, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x93, 0x67, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x33, 0x58,
	0x04, 0xcc, 0x06, 0xe9, 0x2d, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0x96, 0x60, 0x51, 0x60, 0xd6, 0xe0,
	0x0c, 0x82, 0xf2, 0x40, 0x6a, 0x93, 0xf2, 0x53, 0x2a, 0x25, 0x58, 0x15, 0x18, 0x35, 0x78, 0x82,
	0xc0, 0x6c, 0x23, 0x35, 0x2e, 0x96, 0xe0, 0x92, 0xd2, 0x24, 0x21, 0x39, 0x2e, 0x36, 0xcf, 0xbc,
	0xb2, 0xfc, 0xec, 0x54, 0x21, 0x4e, 0x88, 0x73, 0xf4, 0x42, 0x2a, 0xa4, 0x10, 0xcc, 0x24, 0x36,
	0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x9a, 0x66, 0x50, 0xb3, 0x00, 0x00, 0x00,
}
