// Code generated by protoc-gen-gogo.
// source: server.proto
// DO NOT EDIT!

/*
Package proto_api is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	DeleteSessionsRequest
	GetLogsRequest
	FirewallRule
	LoginRequest
	AddSignatoriesRequest
	RemoveSignatoriesRequest
	AddVoteRequest
	CocoonReleasePayloadRequest
	GetCocoonRequest
	GetIdentityRequest
	GetReleaseRequest
	DeployRequest
	CreateIdentityRequest
	StopCocoonRequest
	Response
*/
package proto_api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DeleteSessionsRequest struct {
	All bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
}

func (m *DeleteSessionsRequest) Reset()                    { *m = DeleteSessionsRequest{} }
func (m *DeleteSessionsRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSessionsRequest) ProtoMessage()               {}
func (*DeleteSessionsRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{0} }

func (m *DeleteSessionsRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

type GetLogsRequest struct {
	CocoonID string `protobuf:"bytes,1,opt,name=cocoonID,proto3" json:"cocoonID,omitempty"`
	NumLines int32  `protobuf:"varint,2,opt,name=numLines,proto3" json:"numLines,omitempty"`
	Source   string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
}

func (m *GetLogsRequest) Reset()                    { *m = GetLogsRequest{} }
func (m *GetLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogsRequest) ProtoMessage()               {}
func (*GetLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{1} }

func (m *GetLogsRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *GetLogsRequest) GetNumLines() int32 {
	if m != nil {
		return m.NumLines
	}
	return 0
}

func (m *GetLogsRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type FirewallRule struct {
	Destination     string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	DestinationPort string `protobuf:"bytes,2,opt,name=destinationPort,proto3" json:"destinationPort,omitempty"`
	Protocol        string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (m *FirewallRule) Reset()                    { *m = FirewallRule{} }
func (m *FirewallRule) String() string            { return proto.CompactTextString(m) }
func (*FirewallRule) ProtoMessage()               {}
func (*FirewallRule) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{2} }

func (m *FirewallRule) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *FirewallRule) GetDestinationPort() string {
	if m != nil {
		return m.DestinationPort
	}
	return ""
}

func (m *FirewallRule) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type LoginRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{3} }

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddSignatoriesRequest struct {
	CocoonID string   `protobuf:"bytes,1,opt,name=cocoonID,proto3" json:"cocoonID,omitempty"`
	IDs      []string `protobuf:"bytes,2,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *AddSignatoriesRequest) Reset()                    { *m = AddSignatoriesRequest{} }
func (m *AddSignatoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AddSignatoriesRequest) ProtoMessage()               {}
func (*AddSignatoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{4} }

func (m *AddSignatoriesRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *AddSignatoriesRequest) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type RemoveSignatoriesRequest struct {
	CocoonID string   `protobuf:"bytes,1,opt,name=cocoonID,proto3" json:"cocoonID,omitempty"`
	IDs      []string `protobuf:"bytes,2,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *RemoveSignatoriesRequest) Reset()                    { *m = RemoveSignatoriesRequest{} }
func (m *RemoveSignatoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveSignatoriesRequest) ProtoMessage()               {}
func (*RemoveSignatoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{5} }

func (m *RemoveSignatoriesRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *RemoveSignatoriesRequest) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type AddVoteRequest struct {
	ReleaseID string `protobuf:"bytes,1,opt,name=releaseID,proto3" json:"releaseID,omitempty"`
	Vote      int32  `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (m *AddVoteRequest) Reset()                    { *m = AddVoteRequest{} }
func (m *AddVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*AddVoteRequest) ProtoMessage()               {}
func (*AddVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{6} }

func (m *AddVoteRequest) GetReleaseID() string {
	if m != nil {
		return m.ReleaseID
	}
	return ""
}

func (m *AddVoteRequest) GetVote() int32 {
	if m != nil {
		return m.Vote
	}
	return 0
}

type CocoonReleasePayloadRequest struct {
	CocoonID       string            `protobuf:"bytes,1,opt,name=cocoonID,proto3" json:"cocoonID,omitempty" structs:"cocoonID,omitempty" mapstructure:"cocoonID,omitempty"`
	URL            string            `protobuf:"bytes,2,opt,name=URL,proto3" json:"url,omitempty" structs:"url,omitempty" mapstructure:"url,omitempty"`
	Language       string            `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty" structs:"language,omitempty" mapstructure:"language,omitempty"`
	Version        string            `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty" structs:"version,omitempty" mapstructure:"version,omitempty"`
	BuildParam     string            `protobuf:"bytes,5,opt,name=buildParam,proto3" json:"buildParam,omitempty" structs:"buildParam,omitempty" mapstructure:"buildParam,omitempty"`
	Firewall       []*FirewallRule   `protobuf:"bytes,6,rep,name=firewall" json:"firewall,omitempty" structs:"firewall,omitempty" mapstructure:"firewall,omitempty"`
	ACL            []byte            `protobuf:"bytes,7,opt,name=ACL,proto3" json:"acl,omitempty" structs:"acl,omitempty" mapstructure:"acl,omitempty"`
	Memory         int32             `protobuf:"varint,8,opt,name=memory,proto3" json:"memory,omitempty" structs:"memory,omitempty" mapstructure:"memory,omitempty"`
	CPUShare       int32             `protobuf:"varint,9,opt,name=CPUShare,proto3" json:"CPUShare,omitempty" structs:"CPUShare,omitempty" mapstructure:"CPUShare,omitempty"`
	Link           string            `protobuf:"bytes,10,opt,name=link,proto3" json:"link,omitempty" structs:"link,omitempty" mapstructure:"link,omitempty"`
	NumSignatories int32             `protobuf:"varint,11,opt,name=numSignatories,proto3" json:"numSignatories,omitempty" structs:"numSignatories,omitempty" mapstructure:"numSignatories,omitempty"`
	SigThreshold   int32             `protobuf:"varint,12,opt,name=sigThreshold,proto3" json:"sigThreshold,omitempty" structs:"sigThreshold,omitempty" mapstructure:"sigThreshold,omitempty"`
	Env            map[string]string `protobuf:"bytes,13,rep,name=env" json:"env,omitempty" structs:"env,omitempty" mapstructure:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EnableFirewall bool              `protobuf:"varint,14,opt,name=enableFirewall,proto3" json:"enableFirewall,omitempty" structs:"enableFirewall,omitempty" mapstructure:"enableFirewall,omitempty"`
}

func (m *CocoonReleasePayloadRequest) Reset()         { *m = CocoonReleasePayloadRequest{} }
func (m *CocoonReleasePayloadRequest) String() string { return proto.CompactTextString(m) }
func (*CocoonReleasePayloadRequest) ProtoMessage()    {}
func (*CocoonReleasePayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorServer, []int{7}
}

func (m *CocoonReleasePayloadRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetBuildParam() string {
	if m != nil {
		return m.BuildParam
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetFirewall() []*FirewallRule {
	if m != nil {
		return m.Firewall
	}
	return nil
}

func (m *CocoonReleasePayloadRequest) GetACL() []byte {
	if m != nil {
		return m.ACL
	}
	return nil
}

func (m *CocoonReleasePayloadRequest) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *CocoonReleasePayloadRequest) GetCPUShare() int32 {
	if m != nil {
		return m.CPUShare
	}
	return 0
}

func (m *CocoonReleasePayloadRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CocoonReleasePayloadRequest) GetNumSignatories() int32 {
	if m != nil {
		return m.NumSignatories
	}
	return 0
}

func (m *CocoonReleasePayloadRequest) GetSigThreshold() int32 {
	if m != nil {
		return m.SigThreshold
	}
	return 0
}

func (m *CocoonReleasePayloadRequest) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *CocoonReleasePayloadRequest) GetEnableFirewall() bool {
	if m != nil {
		return m.EnableFirewall
	}
	return false
}

type GetCocoonRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *GetCocoonRequest) Reset()                    { *m = GetCocoonRequest{} }
func (m *GetCocoonRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCocoonRequest) ProtoMessage()               {}
func (*GetCocoonRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{8} }

func (m *GetCocoonRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetIdentityRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ID    string `protobuf:"bytes,2,opt,name=ID,proto3" json:"id" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *GetIdentityRequest) Reset()                    { *m = GetIdentityRequest{} }
func (m *GetIdentityRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIdentityRequest) ProtoMessage()               {}
func (*GetIdentityRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{9} }

func (m *GetIdentityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetIdentityRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetReleaseRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *GetReleaseRequest) Reset()                    { *m = GetReleaseRequest{} }
func (m *GetReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseRequest) ProtoMessage()               {}
func (*GetReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{10} }

func (m *GetReleaseRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeployRequest struct {
	CocoonID  string `protobuf:"bytes,1,opt,name=cocoonID,proto3" json:"cocoonID,omitempty"`
	ReleaseID string `protobuf:"bytes,2,opt,name=releaseID,proto3" json:"releaseID,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{11} }

func (m *DeployRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *DeployRequest) GetReleaseID() string {
	if m != nil {
		return m.ReleaseID
	}
	return ""
}

type CreateIdentityRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *CreateIdentityRequest) Reset()                    { *m = CreateIdentityRequest{} }
func (m *CreateIdentityRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIdentityRequest) ProtoMessage()               {}
func (*CreateIdentityRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{12} }

func (m *CreateIdentityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateIdentityRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StopCocoonRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *StopCocoonRequest) Reset()                    { *m = StopCocoonRequest{} }
func (m *StopCocoonRequest) String() string            { return proto.CompactTextString(m) }
func (*StopCocoonRequest) ProtoMessage()               {}
func (*StopCocoonRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{13} }

func (m *StopCocoonRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Response struct {
	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{14} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteSessionsRequest)(nil), "proto_api.DeleteSessionsRequest")
	proto.RegisterType((*GetLogsRequest)(nil), "proto_api.GetLogsRequest")
	proto.RegisterType((*FirewallRule)(nil), "proto_api.FirewallRule")
	proto.RegisterType((*LoginRequest)(nil), "proto_api.LoginRequest")
	proto.RegisterType((*AddSignatoriesRequest)(nil), "proto_api.AddSignatoriesRequest")
	proto.RegisterType((*RemoveSignatoriesRequest)(nil), "proto_api.RemoveSignatoriesRequest")
	proto.RegisterType((*AddVoteRequest)(nil), "proto_api.AddVoteRequest")
	proto.RegisterType((*CocoonReleasePayloadRequest)(nil), "proto_api.CocoonReleasePayloadRequest")
	proto.RegisterType((*GetCocoonRequest)(nil), "proto_api.GetCocoonRequest")
	proto.RegisterType((*GetIdentityRequest)(nil), "proto_api.GetIdentityRequest")
	proto.RegisterType((*GetReleaseRequest)(nil), "proto_api.GetReleaseRequest")
	proto.RegisterType((*DeployRequest)(nil), "proto_api.DeployRequest")
	proto.RegisterType((*CreateIdentityRequest)(nil), "proto_api.CreateIdentityRequest")
	proto.RegisterType((*StopCocoonRequest)(nil), "proto_api.StopCocoonRequest")
	proto.RegisterType((*Response)(nil), "proto_api.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
	CreateCocoon(ctx context.Context, in *CocoonReleasePayloadRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateCocoon(ctx context.Context, in *CocoonReleasePayloadRequest, opts ...grpc.CallOption) (*Response, error)
	GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Response, error)
	CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Response, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error)
	GetCocoon(ctx context.Context, in *GetCocoonRequest, opts ...grpc.CallOption) (*Response, error)
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Response, error)
	StopCocoon(ctx context.Context, in *StopCocoonRequest, opts ...grpc.CallOption) (*Response, error)
	AddSignatories(ctx context.Context, in *AddSignatoriesRequest, opts ...grpc.CallOption) (*Response, error)
	AddVote(ctx context.Context, in *AddVoteRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveSignatories(ctx context.Context, in *RemoveSignatoriesRequest, opts ...grpc.CallOption) (*Response, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteSessions(ctx context.Context, in *DeleteSessionsRequest, opts ...grpc.CallOption) (*Response, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateCocoon(ctx context.Context, in *CocoonReleasePayloadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/CreateCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateCocoon(ctx context.Context, in *CocoonReleasePayloadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/UpdateCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/GetRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/CreateIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetCocoon(ctx context.Context, in *GetCocoonRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/GetCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/GetIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) StopCocoon(ctx context.Context, in *StopCocoonRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/StopCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddSignatories(ctx context.Context, in *AddSignatoriesRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/AddSignatories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddVote(ctx context.Context, in *AddVoteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/AddVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) RemoveSignatories(ctx context.Context, in *RemoveSignatoriesRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/RemoveSignatories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/GetLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteSessions(ctx context.Context, in *DeleteSessionsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto_api.API/DeleteSessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Login(context.Context, *LoginRequest) (*Response, error)
	CreateCocoon(context.Context, *CocoonReleasePayloadRequest) (*Response, error)
	UpdateCocoon(context.Context, *CocoonReleasePayloadRequest) (*Response, error)
	GetRelease(context.Context, *GetReleaseRequest) (*Response, error)
	CreateIdentity(context.Context, *CreateIdentityRequest) (*Response, error)
	Deploy(context.Context, *DeployRequest) (*Response, error)
	GetCocoon(context.Context, *GetCocoonRequest) (*Response, error)
	GetIdentity(context.Context, *GetIdentityRequest) (*Response, error)
	StopCocoon(context.Context, *StopCocoonRequest) (*Response, error)
	AddSignatories(context.Context, *AddSignatoriesRequest) (*Response, error)
	AddVote(context.Context, *AddVoteRequest) (*Response, error)
	RemoveSignatories(context.Context, *RemoveSignatoriesRequest) (*Response, error)
	GetLogs(context.Context, *GetLogsRequest) (*Response, error)
	DeleteSessions(context.Context, *DeleteSessionsRequest) (*Response, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CocoonReleasePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/CreateCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateCocoon(ctx, req.(*CocoonReleasePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CocoonReleasePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/UpdateCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateCocoon(ctx, req.(*CocoonReleasePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/GetRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetRelease(ctx, req.(*GetReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/CreateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateIdentity(ctx, req.(*CreateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCocoonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/GetCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetCocoon(ctx, req.(*GetCocoonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_StopCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCocoonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).StopCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/StopCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).StopCocoon(ctx, req.(*StopCocoonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddSignatories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSignatoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddSignatories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/AddSignatories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddSignatories(ctx, req.(*AddSignatoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/AddVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddVote(ctx, req.(*AddVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_RemoveSignatories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSignatoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).RemoveSignatories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/RemoveSignatories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).RemoveSignatories(ctx, req.(*RemoveSignatoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_api.API/DeleteSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteSessions(ctx, req.(*DeleteSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _API_Login_Handler,
		},
		{
			MethodName: "CreateCocoon",
			Handler:    _API_CreateCocoon_Handler,
		},
		{
			MethodName: "UpdateCocoon",
			Handler:    _API_UpdateCocoon_Handler,
		},
		{
			MethodName: "GetRelease",
			Handler:    _API_GetRelease_Handler,
		},
		{
			MethodName: "CreateIdentity",
			Handler:    _API_CreateIdentity_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _API_Deploy_Handler,
		},
		{
			MethodName: "GetCocoon",
			Handler:    _API_GetCocoon_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _API_GetIdentity_Handler,
		},
		{
			MethodName: "StopCocoon",
			Handler:    _API_StopCocoon_Handler,
		},
		{
			MethodName: "AddSignatories",
			Handler:    _API_AddSignatories_Handler,
		},
		{
			MethodName: "AddVote",
			Handler:    _API_AddVote_Handler,
		},
		{
			MethodName: "RemoveSignatories",
			Handler:    _API_RemoveSignatories_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _API_GetLogs_Handler,
		},
		{
			MethodName: "DeleteSessions",
			Handler:    _API_DeleteSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptorServer) }

var fileDescriptorServer = []byte{
	// 1174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x97, 0xed, 0x26, 0xb1, 0x27, 0xae, 0x49, 0x96, 0xa6, 0x1c, 0x69, 0x91, 0xad, 0xab, 0x84,
	0x8c, 0x04, 0x89, 0x14, 0x20, 0x40, 0x54, 0x28, 0xf9, 0xd7, 0x60, 0x30, 0x52, 0xb4, 0x21, 0x08,
	0x09, 0x09, 0xb2, 0xf6, 0x4d, 0x9d, 0x6b, 0xef, 0x6e, 0xcd, 0xdd, 0x9e, 0x8b, 0x5f, 0x78, 0xe2,
	0x81, 0x07, 0x78, 0xe1, 0xab, 0xf0, 0x7d, 0xee, 0x03, 0xf8, 0xb1, 0x9f, 0x00, 0xdd, 0xde, 0x1f,
	0xdf, 0xde, 0x9f, 0x28, 0x12, 0xe5, 0xc9, 0x37, 0xf3, 0x9b, 0x9d, 0xdf, 0xcc, 0xec, 0x8c, 0x77,
	0x17, 0xda, 0x1e, 0xba, 0x33, 0x74, 0x77, 0xa6, 0x2e, 0x17, 0x9c, 0xb4, 0xe4, 0xcf, 0xcf, 0x6c,
	0x6a, 0x6e, 0x7f, 0x30, 0x31, 0xc5, 0xb5, 0x3f, 0xda, 0x19, 0x73, 0x7b, 0x77, 0xc2, 0x27, 0x7c,
	0x57, 0x42, 0x23, 0xff, 0x99, 0x94, 0xa4, 0x20, 0xbf, 0xa2, 0x95, 0xfa, 0x7b, 0xb0, 0x75, 0x82,
	0x16, 0x0a, 0xbc, 0x40, 0xcf, 0x33, 0xb9, 0xe3, 0x51, 0xfc, 0xc5, 0x47, 0x4f, 0x90, 0x0d, 0x68,
	0x30, 0xcb, 0xd2, 0x6a, 0xbd, 0x5a, 0xbf, 0x49, 0xc3, 0x4f, 0xfd, 0x0a, 0x3a, 0x67, 0x28, 0x86,
	0x7c, 0x92, 0xda, 0x6c, 0x43, 0x73, 0xcc, 0xc7, 0x9c, 0x3b, 0x83, 0x13, 0x69, 0xd8, 0xa2, 0xa9,
	0x1c, 0x62, 0x8e, 0x6f, 0x0f, 0x4d, 0x07, 0x3d, 0xad, 0xde, 0xab, 0xf5, 0x57, 0x68, 0x2a, 0x93,
	0xfb, 0xb0, 0xea, 0x71, 0xdf, 0x1d, 0xa3, 0xd6, 0x90, 0xab, 0x62, 0x49, 0x9f, 0x41, 0xfb, 0xa9,
	0xe9, 0xe2, 0x4b, 0x66, 0x59, 0xd4, 0xb7, 0x90, 0xf4, 0x60, 0xdd, 0x40, 0x4f, 0x98, 0x0e, 0x13,
	0x26, 0x77, 0x62, 0x8a, 0xac, 0x8a, 0xf4, 0xe1, 0x8d, 0x8c, 0x78, 0xce, 0x5d, 0x21, 0xc9, 0x5a,
	0x34, 0xaf, 0x0e, 0xe3, 0x91, 0x19, 0x8f, 0xb9, 0x15, 0xb3, 0xa6, 0xb2, 0xfe, 0x25, 0xb4, 0x87,
	0x7c, 0x62, 0x3a, 0x49, 0x5e, 0xf7, 0x60, 0x05, 0x6d, 0x66, 0x5a, 0x31, 0x63, 0x24, 0x48, 0x0f,
	0xcc, 0xf3, 0x5e, 0x72, 0xd7, 0x88, 0x49, 0x52, 0x59, 0x3f, 0x85, 0xad, 0x43, 0xc3, 0xb8, 0x30,
	0x27, 0x0e, 0x13, 0xdc, 0x35, 0xf1, 0x56, 0x25, 0xda, 0x80, 0xc6, 0xe0, 0x24, 0xac, 0x4e, 0xa3,
	0xdf, 0xa2, 0xe1, 0xa7, 0xfe, 0x15, 0x68, 0x14, 0x6d, 0x3e, 0xc3, 0xff, 0xec, 0xe9, 0x08, 0x3a,
	0x87, 0x86, 0xf1, 0x3d, 0x17, 0x98, 0xac, 0x7f, 0x08, 0x2d, 0x17, 0x2d, 0x64, 0x1e, 0xa6, 0x0e,
	0x96, 0x0a, 0x42, 0xe0, 0xce, 0x8c, 0x0b, 0x8c, 0xb7, 0x4a, 0x7e, 0xeb, 0xbf, 0x77, 0xe0, 0xc1,
	0xb1, 0xa4, 0xa0, 0x91, 0xdd, 0x39, 0x9b, 0x5b, 0x9c, 0x19, 0x89, 0x47, 0x91, 0x8f, 0xe8, 0xe8,
	0x87, 0x45, 0xd0, 0x25, 0x89, 0xee, 0x7d, 0x6e, 0x9b, 0x02, 0xed, 0xa9, 0x98, 0xbf, 0x0a, 0xba,
	0x5f, 0x78, 0xc2, 0xf5, 0xc7, 0xc2, 0x3b, 0xd0, 0x8b, 0xb0, 0xde, 0xb3, 0xd9, 0x34, 0xc2, 0x7d,
	0x17, 0x4b, 0x2d, 0x32, 0xb9, 0xfe, 0x08, 0x8d, 0x4b, 0x3a, 0x8c, 0x76, 0xe0, 0x68, 0xb0, 0x08,
	0xba, 0x77, 0x7d, 0xd7, 0x52, 0xb8, 0x3e, 0x4a, 0xb9, 0x14, 0x24, 0x4f, 0xa3, 0x82, 0x34, 0xf4,
	0x1a, 0xa6, 0x64, 0x31, 0x67, 0xe2, 0xb3, 0x49, 0xdc, 0x9b, 0x51, 0x4a, 0x89, 0xae, 0x22, 0xa5,
	0x22, 0x9c, 0xe7, 0x2a, 0xb1, 0xa0, 0x29, 0x13, 0xe1, 0xb0, 0x36, 0x43, 0x37, 0x1c, 0x3f, 0xed,
	0x8e, 0x24, 0xbd, 0x5c, 0x04, 0xdd, 0xcd, 0x58, 0xa5, 0x70, 0x3e, 0x4e, 0x39, 0x0b, 0x68, 0x9e,
	0xb2, 0x68, 0x40, 0x13, 0x16, 0xf2, 0x1b, 0xc0, 0xc8, 0x37, 0x2d, 0xe3, 0x9c, 0xb9, 0xcc, 0xd6,
	0x56, 0x24, 0xe7, 0x4f, 0x8b, 0xa0, 0x7b, 0x6f, 0xa9, 0x55, 0x68, 0x8f, 0x52, 0xda, 0x32, 0x83,
	0x3c, 0x73, 0xa9, 0x0d, 0xcd, 0x30, 0x92, 0xbf, 0x6a, 0xd0, 0x7c, 0x16, 0x4f, 0xba, 0xb6, 0xda,
	0x6b, 0xf4, 0xd7, 0xf7, 0xde, 0xda, 0x49, 0xff, 0xc3, 0x76, 0xb2, 0x7f, 0x02, 0xd1, 0x06, 0x24,
	0xc6, 0x15, 0x1b, 0x50, 0x84, 0xf3, 0x31, 0x95, 0x58, 0xd0, 0x34, 0x84, 0xb0, 0xa7, 0x0e, 0x8f,
	0x87, 0xda, 0x5a, 0xaf, 0xd6, 0x6f, 0x47, 0x3d, 0xc5, 0xc6, 0x55, 0x3d, 0xa5, 0x20, 0x79, 0x1a,
	0x15, 0xa4, 0xa1, 0x57, 0xf2, 0x1c, 0x56, 0x6d, 0xb4, 0xb9, 0x3b, 0xd7, 0x9a, 0xe1, 0x70, 0x1d,
	0xd1, 0x45, 0xd0, 0xdd, 0x88, 0x34, 0x0a, 0xc5, 0x41, 0x4a, 0x91, 0x07, 0xf3, 0x2c, 0x05, 0x9c,
	0xc6, 0x0c, 0x61, 0xff, 0x1e, 0x9f, 0x5f, 0x5e, 0x5c, 0x33, 0x17, 0xb5, 0x96, 0x64, 0x93, 0xe5,
	0x4b, 0x74, 0x15, 0xe5, 0x2b, 0xc2, 0x79, 0xc6, 0x12, 0x0b, 0x9a, 0x32, 0x91, 0x2b, 0xb8, 0x63,
	0x99, 0xce, 0x0b, 0x0d, 0x64, 0x23, 0x0d, 0x17, 0x41, 0xb7, 0x13, 0xca, 0x0a, 0xdb, 0xfe, 0x72,
	0x5a, 0x14, 0xa8, 0x30, 0x29, 0x2a, 0x4a, 0xa5, 0x67, 0xf2, 0x77, 0x0d, 0x3a, 0x8e, 0x6f, 0x67,
	0xfe, 0x16, 0xb5, 0x75, 0x99, 0xde, 0xf3, 0x45, 0xd0, 0xd5, 0x54, 0x44, 0xa1, 0xfd, 0x3a, 0xa5,
	0xad, 0x32, 0xca, 0x07, 0x50, 0x69, 0x47, 0x73, 0x11, 0x90, 0x3f, 0x6a, 0xd0, 0xf6, 0xcc, 0xc9,
	0x77, 0xd7, 0x2e, 0x7a, 0xd7, 0xdc, 0x32, 0xb4, 0xb6, 0x0c, 0xc9, 0x58, 0x04, 0xdd, 0xfb, 0x59,
	0xbd, 0x12, 0xd0, 0xd3, 0x34, 0xa0, 0x72, 0x93, 0x7c, 0x38, 0x15, 0x56, 0x54, 0x61, 0x26, 0x7f,
	0xd6, 0xa0, 0x81, 0xce, 0x4c, 0xbb, 0x2b, 0x67, 0x69, 0x37, 0x33, 0x4b, 0x37, 0xfc, 0x81, 0xef,
	0x9c, 0x3a, 0xb3, 0x53, 0x47, 0xb8, 0xf3, 0xa8, 0xe5, 0xd1, 0x99, 0x55, 0xb4, 0xbc, 0x82, 0xe4,
	0x03, 0x54, 0x41, 0x1a, 0x86, 0x21, 0xb7, 0x0b, 0x1d, 0x36, 0xb2, 0x30, 0x19, 0x65, 0xad, 0x13,
	0x5e, 0x24, 0xa2, 0xed, 0x52, 0x91, 0x8a, 0xed, 0xaa, 0x32, 0x2a, 0xd2, 0x57, 0xd8, 0xd1, 0x5c,
	0x04, 0xdb, 0xfb, 0xd0, 0x4c, 0x12, 0x0e, 0x0f, 0xcc, 0x17, 0x38, 0x8f, 0x8f, 0xc1, 0xf0, 0x33,
	0x3c, 0xf3, 0x67, 0xcc, 0xf2, 0x31, 0x3e, 0xda, 0x23, 0xe1, 0xa0, 0xfe, 0x69, 0x4d, 0xbf, 0x82,
	0x8d, 0x33, 0x14, 0x49, 0x1d, 0xa3, 0xa3, 0x6f, 0x08, 0xf5, 0xf4, 0xd0, 0x7b, 0xbc, 0x08, 0xba,
	0x75, 0xd3, 0x78, 0x15, 0x74, 0xf7, 0xd2, 0xe8, 0xcd, 0x1b, 0x76, 0x54, 0xc1, 0x68, 0x7d, 0x70,
	0xa2, 0xff, 0x0a, 0xe4, 0x0c, 0xc5, 0xc0, 0x40, 0x47, 0x98, 0x62, 0x7e, 0xf3, 0x2d, 0x24, 0x62,
	0xae, 0xbf, 0x26, 0xe6, 0x47, 0xb0, 0x79, 0x86, 0x22, 0xee, 0x8e, 0x84, 0xb8, 0xb3, 0x4c, 0x4e,
	0x1a, 0x0d, 0xe0, 0xee, 0x09, 0x4e, 0x2d, 0x3e, 0xbf, 0xcd, 0x55, 0x44, 0xb9, 0x66, 0xd4, 0x73,
	0xd7, 0x0c, 0x7d, 0x00, 0x5b, 0xc7, 0x2e, 0x32, 0x81, 0xb7, 0x4b, 0xf6, 0xa6, 0x2b, 0x17, 0x83,
	0xcd, 0x0b, 0xc1, 0xa7, 0xff, 0xe7, 0xbe, 0xec, 0x43, 0x93, 0xa2, 0x37, 0xe5, 0x8e, 0x87, 0xf2,
	0xce, 0x2a, 0x98, 0xf0, 0x3d, 0xe9, 0x7d, 0x85, 0xc6, 0x52, 0x78, 0x71, 0x1a, 0x71, 0x63, 0x2e,
	0xc3, 0x6b, 0x53, 0xf9, 0xbd, 0xf7, 0xcf, 0x1a, 0x34, 0x0e, 0xcf, 0x07, 0xe4, 0x63, 0x58, 0x91,
	0xf7, 0x4a, 0x92, 0x3d, 0xdc, 0xb2, 0x37, 0xcd, 0xed, 0x37, 0x33, 0x40, 0x4a, 0xf5, 0x0d, 0xb4,
	0xa3, 0x22, 0x45, 0xb9, 0x91, 0x77, 0x6f, 0x37, 0xce, 0x95, 0xce, 0x2e, 0xa7, 0xc6, 0x6b, 0x72,
	0xf6, 0x04, 0x60, 0xd9, 0x2e, 0xe4, 0x61, 0xc6, 0xa4, 0xd0, 0x45, 0xe5, 0x0e, 0xce, 0xa0, 0xa3,
	0xee, 0x3f, 0xe9, 0x65, 0xe3, 0x29, 0x6b, 0x8d, 0x72, 0x47, 0x9f, 0xc0, 0x6a, 0xd4, 0x93, 0x44,
	0xcb, 0xc0, 0x4a, 0x9b, 0x96, 0x2f, 0xfc, 0x1c, 0x5a, 0xe9, 0x34, 0x93, 0x07, 0x6a, 0x06, 0x4a,
	0x2f, 0x95, 0x2f, 0x3f, 0x84, 0xf5, 0xcc, 0xa8, 0x92, 0x77, 0x54, 0x07, 0xb7, 0x0a, 0xfd, 0x09,
	0xc0, 0xb2, 0x71, 0x95, 0x22, 0x16, 0xfa, 0xb9, 0xb2, 0x88, 0xea, 0x63, 0x43, 0x29, 0x62, 0xe9,
	0x3b, 0xa4, 0xdc, 0xd1, 0x67, 0xb0, 0x16, 0x3f, 0x12, 0xc8, 0xdb, 0xaa, 0x87, 0xcc, 0xc3, 0xa1,
	0x7c, 0xe9, 0xb7, 0xb0, 0x59, 0x78, 0xa9, 0x90, 0x47, 0x8a, 0x65, 0xf9, 0x3b, 0xa6, 0x32, 0x92,
	0xf8, 0x6d, 0xa9, 0x44, 0xa2, 0xbe, 0x37, 0x2b, 0xab, 0xa1, 0xbe, 0x60, 0x95, 0x6a, 0x94, 0x3e,
	0x6e, 0x4b, 0x1d, 0x8d, 0x56, 0xa5, 0xee, 0xc3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x12,
	0x00, 0x80, 0x5b, 0x0f, 0x00, 0x00,
}
