// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto_runtime is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Ok
	InvokeParam
	InvokeResponse
*/
package proto_runtime

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ok struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Ok) Reset()                    { *m = Ok{} }
func (m *Ok) String() string            { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()               {}
func (*Ok) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ok) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InvokeParam struct {
	ID       string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Function string   `protobuf:"bytes,2,opt,name=function" json:"function,omitempty"`
	Params   []string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty"`
}

func (m *InvokeParam) Reset()                    { *m = InvokeParam{} }
func (m *InvokeParam) String() string            { return proto.CompactTextString(m) }
func (*InvokeParam) ProtoMessage()               {}
func (*InvokeParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InvokeParam) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *InvokeParam) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *InvokeParam) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type InvokeResponse struct {
	ID     string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *InvokeResponse) Reset()                    { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string            { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()               {}
func (*InvokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InvokeResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *InvokeResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InvokeResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Ok)(nil), "proto_runtime.Ok")
	proto.RegisterType((*InvokeParam)(nil), "proto_runtime.InvokeParam")
	proto.RegisterType((*InvokeResponse)(nil), "proto_runtime.InvokeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stub service

type StubClient interface {
	HealthCheck(ctx context.Context, in *Ok, opts ...grpc.CallOption) (*Ok, error)
	Invoke(ctx context.Context, in *InvokeParam, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type stubClient struct {
	cc *grpc.ClientConn
}

func NewStubClient(cc *grpc.ClientConn) StubClient {
	return &stubClient{cc}
}

func (c *stubClient) HealthCheck(ctx context.Context, in *Ok, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/proto_runtime.Stub/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stubClient) Invoke(ctx context.Context, in *InvokeParam, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := grpc.Invoke(ctx, "/proto_runtime.Stub/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stub service

type StubServer interface {
	HealthCheck(context.Context, *Ok) (*Ok, error)
	Invoke(context.Context, *InvokeParam) (*InvokeResponse, error)
}

func RegisterStubServer(s *grpc.Server, srv StubServer) {
	s.RegisterService(&_Stub_serviceDesc, srv)
}

func _Stub_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ok)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StubServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_runtime.Stub/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StubServer).HealthCheck(ctx, req.(*Ok))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stub_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StubServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_runtime.Stub/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StubServer).Invoke(ctx, req.(*InvokeParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_runtime.Stub",
	HandlerType: (*StubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Stub_HealthCheck_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _Stub_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0x53, 0xf1, 0x45, 0xa5, 0x79,
	0x25, 0x99, 0xb9, 0xa9, 0x4a, 0x32, 0x5c, 0x4c, 0xfe, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25,
	0x89, 0x25, 0xa5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x52, 0x20, 0x17,
	0xb7, 0x67, 0x5e, 0x59, 0x7e, 0x76, 0x6a, 0x40, 0x62, 0x51, 0x62, 0xae, 0x10, 0x1f, 0x17, 0x93,
	0xa7, 0x0b, 0x58, 0x09, 0x67, 0x10, 0x93, 0xa7, 0x8b, 0x90, 0x14, 0x17, 0x47, 0x5a, 0x69, 0x5e,
	0x72, 0x49, 0x66, 0x7e, 0x9e, 0x04, 0x13, 0x58, 0x14, 0xce, 0x07, 0x19, 0x59, 0x00, 0xd2, 0x54,
	0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0xe5, 0x29, 0xf9, 0x70, 0xf1, 0x41, 0x8c, 0x0c,
	0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x30, 0x15, 0xe1, 0x18, 0x26, 0x64, 0xc7, 0x08,
	0x09, 0x71, 0xb1, 0x24, 0xe5, 0xa7, 0x54, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9,
	0x46, 0x0d, 0x8c, 0x5c, 0x2c, 0xc1, 0x25, 0xa5, 0x49, 0x42, 0xc6, 0x5c, 0xdc, 0x1e, 0xa9, 0x89,
	0x39, 0x25, 0x19, 0xce, 0x19, 0xa9, 0xc9, 0xd9, 0x42, 0x82, 0x7a, 0x28, 0xde, 0xd4, 0xf3, 0xcf,
	0x96, 0xc2, 0x14, 0x12, 0x72, 0xe6, 0x62, 0x83, 0xb8, 0x45, 0x48, 0x0a, 0x4d, 0x12, 0xc9, 0xd7,
	0x52, 0xb2, 0x58, 0xe5, 0x60, 0xce, 0x4f, 0x62, 0x03, 0xcb, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0xba, 0xa3, 0x51, 0x67, 0x01, 0x00, 0x00,
}
