// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Tx
	Op
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Tx struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto1.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tx) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tx) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tx) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Op struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Op) Reset()                    { *m = Op{} }
func (m *Op) String() string            { return proto1.CompactTextString(m) }
func (*Op) ProtoMessage()               {}
func (*Op) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Op) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Op) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto1.RegisterType((*Tx)(nil), "proto.Tx")
	proto1.RegisterType((*Op)(nil), "proto.Op")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stub service

type StubClient interface {
	Transact(ctx context.Context, opts ...grpc.CallOption) (Stub_TransactClient, error)
}

type stubClient struct {
	cc *grpc.ClientConn
}

func NewStubClient(cc *grpc.ClientConn) StubClient {
	return &stubClient{cc}
}

func (c *stubClient) Transact(ctx context.Context, opts ...grpc.CallOption) (Stub_TransactClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Stub_serviceDesc.Streams[0], c.cc, "/proto.Stub/Transact", opts...)
	if err != nil {
		return nil, err
	}
	x := &stubTransactClient{stream}
	return x, nil
}

type Stub_TransactClient interface {
	Send(*Op) error
	Recv() (*Tx, error)
	grpc.ClientStream
}

type stubTransactClient struct {
	grpc.ClientStream
}

func (x *stubTransactClient) Send(m *Op) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stubTransactClient) Recv() (*Tx, error) {
	m := new(Tx)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Stub service

type StubServer interface {
	Transact(Stub_TransactServer) error
}

func RegisterStubServer(s *grpc.Server, srv StubServer) {
	s.RegisterService(&_Stub_serviceDesc, srv)
}

func _Stub_Transact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StubServer).Transact(&stubTransactServer{stream})
}

type Stub_TransactServer interface {
	Send(*Tx) error
	Recv() (*Op, error)
	grpc.ServerStream
}

type stubTransactServer struct {
	grpc.ServerStream
}

func (x *stubTransactServer) Send(m *Tx) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stubTransactServer) Recv() (*Op, error) {
	m := new(Op)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Stub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Stub",
	HandlerType: (*StubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transact",
			Handler:       _Stub_Transact_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x76, 0x5c, 0x4c,
	0x21, 0x15, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c,
	0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x11, 0x30, 0x5b,
	0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x19, 0x2c, 0x08, 0xe1, 0x28, 0xe9,
	0x71, 0x31, 0xf9, 0x17, 0xc0, 0xd5, 0x33, 0x62, 0x53, 0xcf, 0x84, 0xa4, 0xde, 0x48, 0x87, 0x8b,
	0x25, 0xb8, 0xa4, 0x34, 0x49, 0x48, 0x85, 0x8b, 0x23, 0xa4, 0x28, 0x31, 0xaf, 0x38, 0x31, 0xb9,
	0x44, 0x88, 0x13, 0xe2, 0x24, 0x3d, 0xff, 0x02, 0x29, 0x18, 0x33, 0xa4, 0x42, 0x83, 0xd1, 0x80,
	0x31, 0x89, 0x0d, 0xcc, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x91, 0x90, 0x1e, 0xbb,
	0x00, 0x00, 0x00,
}
