// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	DeployRequest
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url        string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Language   string `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	ReleaseTag string `protobuf:"bytes,4,opt,name=releaseTag" json:"releaseTag,omitempty"`
	BuildParam []byte `protobuf:"bytes,5,opt,name=buildParam,proto3" json:"buildParam,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeployRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DeployRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DeployRequest) GetReleaseTag() string {
	if m != nil {
		return m.ReleaseTag
	}
	return ""
}

func (m *DeployRequest) GetBuildParam() []byte {
	if m != nil {
		return m.BuildParam
	}
	return nil
}

type Response struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto1.RegisterType((*DeployRequest)(nil), "proto.DeployRequest")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Deploy(context.Context, *DeployRequest) (*Response, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _API_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4a, 0xc4, 0x40,
	0x10, 0x84, 0x99, 0x64, 0x13, 0xd6, 0x26, 0xfe, 0xd0, 0x88, 0x0c, 0x7b, 0x90, 0x65, 0x4f, 0x7b,
	0x5a, 0x41, 0x61, 0xef, 0x82, 0x17, 0x6f, 0x61, 0xf0, 0x05, 0x26, 0x4c, 0x13, 0x02, 0x63, 0x26,
	0xce, 0x8f, 0x90, 0x87, 0xf0, 0x9d, 0x25, 0x9d, 0x28, 0xd9, 0x53, 0x57, 0x7d, 0x75, 0xe8, 0x2a,
	0xa8, 0x02, 0xf9, 0x6f, 0xf2, 0xa7, 0xc1, 0xbb, 0xe8, 0xb0, 0xe0, 0x73, 0xf8, 0x11, 0x70, 0xfd,
	0x46, 0x83, 0x75, 0xa3, 0xa2, 0xaf, 0x44, 0x21, 0xe2, 0x0d, 0x64, 0x9d, 0x91, 0x62, 0x2f, 0x8e,
	0x57, 0x2a, 0xeb, 0x0c, 0xde, 0x41, 0x9e, 0xbc, 0x95, 0x19, 0x83, 0x49, 0xe2, 0x0e, 0xb6, 0x56,
	0xf7, 0x6d, 0xd2, 0x2d, 0xc9, 0x9c, 0xf1, 0xbf, 0xc7, 0x47, 0x00, 0x4f, 0x96, 0x74, 0xa0, 0x0f,
	0xdd, 0xca, 0x0d, 0xa7, 0x2b, 0x32, 0xe5, 0x4d, 0xea, 0xac, 0xa9, 0xb5, 0xd7, 0x9f, 0xb2, 0xd8,
	0x8b, 0x63, 0xa5, 0x56, 0xe4, 0x70, 0x86, 0xad, 0xa2, 0x30, 0xb8, 0x3e, 0x10, 0x3e, 0x40, 0x19,
	0xa2, 0x8e, 0x29, 0x70, 0x9b, 0x42, 0x2d, 0x0e, 0x11, 0x36, 0x8d, 0x33, 0x23, 0x57, 0xaa, 0x14,
	0xeb, 0xe7, 0x33, 0xe4, 0xaf, 0xf5, 0x3b, 0x3e, 0x41, 0x39, 0xaf, 0xc1, 0xfb, 0x79, 0xe7, 0xe9,
	0x62, 0xdc, 0xee, 0x76, 0xa1, 0x7f, 0x3f, 0x9a, 0x92, 0xfd, 0xcb, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0xde, 0xb9, 0xe8, 0x1d, 0x01, 0x00, 0x00,
}
