// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	CreateCocoonRequest
	GetCocoonRequest
	CreateReleaseRequest
	DeployRequest
	CreateIdentityRequest
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCocoonRequest struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url          string   `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Language     string   `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	ReleaseTag   string   `protobuf:"bytes,4,opt,name=releaseTag" json:"releaseTag,omitempty"`
	BuildParam   []byte   `protobuf:"bytes,5,opt,name=buildParam,proto3" json:"buildParam,omitempty"`
	Memory       string   `protobuf:"bytes,6,opt,name=memory" json:"memory,omitempty"`
	CPUShare     string   `protobuf:"bytes,7,opt,name=CPUShare" json:"CPUShare,omitempty"`
	Releases     []string `protobuf:"bytes,8,rep,name=releases" json:"releases,omitempty"`
	Instances    int32    `protobuf:"varint,9,opt,name=instances" json:"instances,omitempty"`
	Signers      int32    `protobuf:"varint,10,opt,name=signers" json:"signers,omitempty"`
	SigThreshold int32    `protobuf:"varint,11,opt,name=sigThreshold" json:"sigThreshold,omitempty"`
}

func (m *CreateCocoonRequest) Reset()                    { *m = CreateCocoonRequest{} }
func (m *CreateCocoonRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateCocoonRequest) ProtoMessage()               {}
func (*CreateCocoonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateCocoonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateCocoonRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateCocoonRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CreateCocoonRequest) GetReleaseTag() string {
	if m != nil {
		return m.ReleaseTag
	}
	return ""
}

func (m *CreateCocoonRequest) GetBuildParam() []byte {
	if m != nil {
		return m.BuildParam
	}
	return nil
}

func (m *CreateCocoonRequest) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *CreateCocoonRequest) GetCPUShare() string {
	if m != nil {
		return m.CPUShare
	}
	return ""
}

func (m *CreateCocoonRequest) GetReleases() []string {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *CreateCocoonRequest) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *CreateCocoonRequest) GetSigners() int32 {
	if m != nil {
		return m.Signers
	}
	return 0
}

func (m *CreateCocoonRequest) GetSigThreshold() int32 {
	if m != nil {
		return m.SigThreshold
	}
	return 0
}

type GetCocoonRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetCocoonRequest) Reset()                    { *m = GetCocoonRequest{} }
func (m *GetCocoonRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCocoonRequest) ProtoMessage()               {}
func (*GetCocoonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetCocoonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateReleaseRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CocoonID    string `protobuf:"bytes,2,opt,name=cocoonID" json:"cocoonID,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Language    string `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	ReleaseTag  string `protobuf:"bytes,5,opt,name=releaseTag" json:"releaseTag,omitempty"`
	BuildParam  []byte `protobuf:"bytes,6,opt,name=buildParam,proto3" json:"buildParam,omitempty"`
	SigApproved int32  `protobuf:"varint,7,opt,name=sigApproved" json:"sigApproved,omitempty"`
	SigDenied   int32  `protobuf:"varint,8,opt,name=sigDenied" json:"sigDenied,omitempty"`
}

func (m *CreateReleaseRequest) Reset()                    { *m = CreateReleaseRequest{} }
func (m *CreateReleaseRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateReleaseRequest) ProtoMessage()               {}
func (*CreateReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateReleaseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateReleaseRequest) GetCocoonID() string {
	if m != nil {
		return m.CocoonID
	}
	return ""
}

func (m *CreateReleaseRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateReleaseRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CreateReleaseRequest) GetReleaseTag() string {
	if m != nil {
		return m.ReleaseTag
	}
	return ""
}

func (m *CreateReleaseRequest) GetBuildParam() []byte {
	if m != nil {
		return m.BuildParam
	}
	return nil
}

func (m *CreateReleaseRequest) GetSigApproved() int32 {
	if m != nil {
		return m.SigApproved
	}
	return 0
}

func (m *CreateReleaseRequest) GetSigDenied() int32 {
	if m != nil {
		return m.SigDenied
	}
	return 0
}

type DeployRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url        string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Language   string `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	ReleaseTag string `protobuf:"bytes,4,opt,name=releaseTag" json:"releaseTag,omitempty"`
	BuildParam []byte `protobuf:"bytes,5,opt,name=buildParam,proto3" json:"buildParam,omitempty"`
	Memory     string `protobuf:"bytes,6,opt,name=memory" json:"memory,omitempty"`
	CpuShare   string `protobuf:"bytes,7,opt,name=cpuShare" json:"cpuShare,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeployRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeployRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DeployRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DeployRequest) GetReleaseTag() string {
	if m != nil {
		return m.ReleaseTag
	}
	return ""
}

func (m *DeployRequest) GetBuildParam() []byte {
	if m != nil {
		return m.BuildParam
	}
	return nil
}

func (m *DeployRequest) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *DeployRequest) GetCpuShare() string {
	if m != nil {
		return m.CpuShare
	}
	return ""
}

type CreateIdentityRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PubKey string `protobuf:"bytes,3,opt,name=pubKey" json:"pubKey,omitempty"`
}

func (m *CreateIdentityRequest) Reset()                    { *m = CreateIdentityRequest{} }
func (m *CreateIdentityRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateIdentityRequest) ProtoMessage()               {}
func (*CreateIdentityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateIdentityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateIdentityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateIdentityRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type Response struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto1.RegisterType((*CreateCocoonRequest)(nil), "proto.CreateCocoonRequest")
	proto1.RegisterType((*GetCocoonRequest)(nil), "proto.GetCocoonRequest")
	proto1.RegisterType((*CreateReleaseRequest)(nil), "proto.CreateReleaseRequest")
	proto1.RegisterType((*DeployRequest)(nil), "proto.DeployRequest")
	proto1.RegisterType((*CreateIdentityRequest)(nil), "proto.CreateIdentityRequest")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	CreateCocoon(ctx context.Context, in *CreateCocoonRequest, opts ...grpc.CallOption) (*Response, error)
	CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Response, error)
	CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Response, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error)
	GetCocoon(ctx context.Context, in *GetCocoonRequest, opts ...grpc.CallOption) (*Response, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateCocoon(ctx context.Context, in *CreateCocoonRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/CreateCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/CreateRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/CreateIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetCocoon(ctx context.Context, in *GetCocoonRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.API/GetCocoon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	CreateCocoon(context.Context, *CreateCocoonRequest) (*Response, error)
	CreateRelease(context.Context, *CreateReleaseRequest) (*Response, error)
	CreateIdentity(context.Context, *CreateIdentityRequest) (*Response, error)
	Deploy(context.Context, *DeployRequest) (*Response, error)
	GetCocoon(context.Context, *GetCocoonRequest) (*Response, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCocoonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateCocoon(ctx, req.(*CreateCocoonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRelease(ctx, req.(*CreateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateIdentity(ctx, req.(*CreateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetCocoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCocoonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetCocoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetCocoon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetCocoon(ctx, req.(*GetCocoonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCocoon",
			Handler:    _API_CreateCocoon_Handler,
		},
		{
			MethodName: "CreateRelease",
			Handler:    _API_CreateRelease_Handler,
		},
		{
			MethodName: "CreateIdentity",
			Handler:    _API_CreateIdentity_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _API_Deploy_Handler,
		},
		{
			MethodName: "GetCocoon",
			Handler:    _API_GetCocoon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0xd8, 0x75, 0xa6, 0x6e, 0xa9, 0x96, 0x50, 0x56, 0xa1, 0x42, 0x96, 0x4f, 0x39,
	0x15, 0x09, 0xc4, 0x09, 0x21, 0x54, 0x25, 0x02, 0x45, 0x5c, 0x22, 0xd3, 0x7e, 0xc0, 0x26, 0x1e,
	0x39, 0x2b, 0x39, 0x5e, 0xb3, 0x6b, 0x57, 0xca, 0x2f, 0xf1, 0x13, 0x88, 0x3f, 0xe2, 0x13, 0x90,
	0xd7, 0x6b, 0x13, 0xd7, 0x6d, 0xb8, 0x72, 0xb2, 0xdf, 0x7b, 0x9a, 0x99, 0x9d, 0x37, 0x33, 0x10,
	0x28, 0x94, 0xf7, 0x28, 0xaf, 0x0b, 0x29, 0x4a, 0x41, 0x5c, 0xfd, 0x89, 0x7e, 0xda, 0xf0, 0x7c,
	0x2e, 0x91, 0x95, 0x38, 0x17, 0x1b, 0x21, 0xf2, 0x18, 0xbf, 0x57, 0xa8, 0x4a, 0x72, 0x0e, 0x36,
	0x4f, 0xa8, 0x15, 0x5a, 0xb3, 0x71, 0x6c, 0xf3, 0x84, 0x5c, 0x80, 0x53, 0xc9, 0x8c, 0xda, 0x9a,
	0xa8, 0x7f, 0xc9, 0x14, 0xfc, 0x8c, 0xe5, 0x69, 0xc5, 0x52, 0xa4, 0x8e, 0xa6, 0x3b, 0x4c, 0x5e,
	0x03, 0x48, 0xcc, 0x90, 0x29, 0xbc, 0x65, 0x29, 0x1d, 0x69, 0xf5, 0x80, 0xa9, 0xf5, 0x75, 0xc5,
	0xb3, 0x64, 0xc5, 0x24, 0xdb, 0x51, 0x37, 0xb4, 0x66, 0x41, 0x7c, 0xc0, 0x90, 0x4b, 0xf0, 0x76,
	0xb8, 0x13, 0x72, 0x4f, 0x3d, 0x1d, 0x6b, 0x50, 0x5d, 0x73, 0xbe, 0xba, 0xfb, 0xb6, 0x65, 0x12,
	0xe9, 0x49, 0x53, 0xb3, 0xc5, 0xb5, 0x66, 0x2a, 0x28, 0xea, 0x87, 0x4e, 0xad, 0xb5, 0x98, 0x5c,
	0xc1, 0x98, 0xe7, 0xaa, 0x64, 0xf9, 0x06, 0x15, 0x1d, 0x87, 0xd6, 0xcc, 0x8d, 0xff, 0x12, 0x84,
	0xc2, 0x89, 0xe2, 0x69, 0x8e, 0x52, 0x51, 0xd0, 0x5a, 0x0b, 0x49, 0x04, 0x81, 0xe2, 0xe9, 0xed,
	0x56, 0xa2, 0xda, 0x8a, 0x2c, 0xa1, 0xa7, 0x5a, 0xee, 0x71, 0x51, 0x04, 0x17, 0x5f, 0xb0, 0x3c,
	0xea, 0x5e, 0xf4, 0xdb, 0x82, 0x49, 0xe3, 0x72, 0xdc, 0x3c, 0xe9, 0x29, 0x9b, 0xa7, 0xe0, 0x6f,
	0x74, 0xa6, 0xe5, 0xc2, 0x78, 0xdd, 0xe1, 0x76, 0x04, 0xce, 0xe3, 0x23, 0x18, 0x1d, 0x1d, 0x81,
	0xfb, 0x8f, 0x11, 0x78, 0x83, 0x11, 0x84, 0x70, 0xaa, 0x78, 0x7a, 0x53, 0x14, 0x52, 0xdc, 0x63,
	0xa2, 0xdd, 0x76, 0xe3, 0x43, 0xaa, 0x36, 0x55, 0xf1, 0x74, 0x81, 0x39, 0xc7, 0x84, 0xfa, 0x8d,
	0xa9, 0x1d, 0x11, 0xfd, 0xb2, 0xe0, 0x6c, 0x81, 0x45, 0x26, 0xf6, 0xff, 0xfd, 0x4a, 0x6d, 0x8a,
	0xaa, 0xb7, 0x52, 0x2d, 0x8e, 0xee, 0xe0, 0x45, 0x33, 0xb5, 0x65, 0x82, 0x79, 0xc9, 0xcb, 0x27,
	0x5b, 0x99, 0x80, 0x8b, 0x3b, 0xc6, 0xdb, 0x66, 0x1a, 0x50, 0x97, 0x2c, 0xaa, 0xf5, 0x57, 0xdc,
	0x9b, 0x66, 0x0c, 0x8a, 0x3e, 0x83, 0x1f, 0xa3, 0x2a, 0x44, 0xae, 0x70, 0x90, 0xe9, 0x12, 0x3c,
	0x55, 0xb2, 0xb2, 0x52, 0x3a, 0x95, 0x1b, 0x1b, 0x44, 0x08, 0x8c, 0xd6, 0x22, 0x69, 0x32, 0x05,
	0xb1, 0xfe, 0x7f, 0xfb, 0xc3, 0x06, 0xe7, 0x66, 0xb5, 0x24, 0x1f, 0x20, 0x38, 0x3c, 0x61, 0x32,
	0x6d, 0x4e, 0xfc, 0xfa, 0x91, 0xbb, 0x9e, 0x3e, 0x33, 0x5a, 0xf7, 0x80, 0x8f, 0x70, 0xd6, 0xdb,
	0x4c, 0xf2, 0xaa, 0x17, 0xdd, 0xdf, 0xd7, 0x61, 0xf8, 0x27, 0x38, 0xef, 0x5b, 0x44, 0xae, 0x7a,
	0xf1, 0x0f, 0x9c, 0x1b, 0x26, 0x78, 0x03, 0x5e, 0xb3, 0x26, 0x64, 0x62, 0xa4, 0xde, 0xd6, 0x0c,
	0x03, 0xde, 0xc3, 0xb8, 0xbb, 0x37, 0xf2, 0xd2, 0xa8, 0x0f, 0x2f, 0x70, 0x10, 0xb6, 0xf6, 0x34,
	0x7e, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x14, 0x93, 0x04, 0xd9, 0x06, 0x05, 0x00, 0x00,
}
