// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	CreateLedgerParams
	PutTransactionParams
	GetLedgerParams
	GetParams
	Ledger
	Transaction
	PutResult
	Block
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateLedgerParams struct {
	CocoonCodeId string `protobuf:"bytes,1,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Public       bool   `protobuf:"varint,3,opt,name=public" json:"public,omitempty"`
	Chained      bool   `protobuf:"varint,4,opt,name=chained" json:"chained,omitempty"`
}

func (m *CreateLedgerParams) Reset()                    { *m = CreateLedgerParams{} }
func (m *CreateLedgerParams) String() string            { return proto1.CompactTextString(m) }
func (*CreateLedgerParams) ProtoMessage()               {}
func (*CreateLedgerParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateLedgerParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *CreateLedgerParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLedgerParams) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *CreateLedgerParams) GetChained() bool {
	if m != nil {
		return m.Chained
	}
	return false
}

type PutTransactionParams struct {
	CocoonCodeId string         `protobuf:"bytes,1,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	LedgerName   string         `protobuf:"bytes,2,opt,name=ledgerName" json:"ledgerName,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *PutTransactionParams) Reset()                    { *m = PutTransactionParams{} }
func (m *PutTransactionParams) String() string            { return proto1.CompactTextString(m) }
func (*PutTransactionParams) ProtoMessage()               {}
func (*PutTransactionParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutTransactionParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *PutTransactionParams) GetLedgerName() string {
	if m != nil {
		return m.LedgerName
	}
	return ""
}

func (m *PutTransactionParams) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetLedgerParams struct {
	CocoonCodeId string `protobuf:"bytes,1,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetLedgerParams) Reset()                    { *m = GetLedgerParams{} }
func (m *GetLedgerParams) String() string            { return proto1.CompactTextString(m) }
func (*GetLedgerParams) ProtoMessage()               {}
func (*GetLedgerParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetLedgerParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *GetLedgerParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetParams struct {
	CocoonCodeId string `protobuf:"bytes,1,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	Key          string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Ledger       string `protobuf:"bytes,3,opt,name=ledger" json:"ledger,omitempty"`
}

func (m *GetParams) Reset()                    { *m = GetParams{} }
func (m *GetParams) String() string            { return proto1.CompactTextString(m) }
func (*GetParams) ProtoMessage()               {}
func (*GetParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *GetParams) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetParams) GetLedger() string {
	if m != nil {
		return m.Ledger
	}
	return ""
}

type Ledger struct {
	Number         int64  `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Hash           string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	PrevLedgerHash string `protobuf:"bytes,3,opt,name=prevLedgerHash" json:"prevLedgerHash,omitempty"`
	NextLedgerHash string `protobuf:"bytes,4,opt,name=nextLedgerHash" json:"nextLedgerHash,omitempty"`
	Name           string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Public         bool   `protobuf:"varint,6,opt,name=public" json:"public,omitempty"`
	Chained        bool   `protobuf:"varint,7,opt,name=chained" json:"chained,omitempty"`
	CreatedAt      int64  `protobuf:"varint,8,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Ledger) Reset()                    { *m = Ledger{} }
func (m *Ledger) String() string            { return proto1.CompactTextString(m) }
func (*Ledger) ProtoMessage()               {}
func (*Ledger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ledger) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Ledger) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Ledger) GetPrevLedgerHash() string {
	if m != nil {
		return m.PrevLedgerHash
	}
	return ""
}

func (m *Ledger) GetNextLedgerHash() string {
	if m != nil {
		return m.NextLedgerHash
	}
	return ""
}

func (m *Ledger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ledger) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Ledger) GetChained() bool {
	if m != nil {
		return m.Chained
	}
	return false
}

func (m *Ledger) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Transaction struct {
	Number    int64  `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Ledger    string `protobuf:"bytes,2,opt,name=ledger" json:"ledger,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Key       string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Value     string `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Hash      string `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	CreatedAt int64  `protobuf:"varint,9,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Transaction) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Transaction) GetLedger() string {
	if m != nil {
		return m.Ledger
	}
	return ""
}

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type PutResult struct {
	Added int32  `protobuf:"varint,1,opt,name=added" json:"added,omitempty"`
	Block *Block `protobuf:"bytes,2,opt,name=block" json:"block,omitempty"`
}

func (m *PutResult) Reset()                    { *m = PutResult{} }
func (m *PutResult) String() string            { return proto1.CompactTextString(m) }
func (*PutResult) ProtoMessage()               {}
func (*PutResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PutResult) GetAdded() int32 {
	if m != nil {
		return m.Added
	}
	return 0
}

func (m *PutResult) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Block struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Number        int64  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	ChainName     string `protobuf:"bytes,3,opt,name=chainName" json:"chainName,omitempty"`
	PrevBlockHash string `protobuf:"bytes,4,opt,name=prevBlockHash" json:"prevBlockHash,omitempty"`
	Hash          string `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	Transactions  []byte `protobuf:"bytes,6,opt,name=transactions,proto3" json:"transactions,omitempty"`
	CreatedAt     int64  `protobuf:"varint,7,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto1.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetTransactions() []byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto1.RegisterType((*CreateLedgerParams)(nil), "proto.CreateLedgerParams")
	proto1.RegisterType((*PutTransactionParams)(nil), "proto.PutTransactionParams")
	proto1.RegisterType((*GetLedgerParams)(nil), "proto.GetLedgerParams")
	proto1.RegisterType((*GetParams)(nil), "proto.GetParams")
	proto1.RegisterType((*Ledger)(nil), "proto.Ledger")
	proto1.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto1.RegisterType((*PutResult)(nil), "proto.PutResult")
	proto1.RegisterType((*Block)(nil), "proto.Block")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Orderer service

type OrdererClient interface {
	CreateLedger(ctx context.Context, in *CreateLedgerParams, opts ...grpc.CallOption) (*Ledger, error)
	GetLedger(ctx context.Context, in *GetLedgerParams, opts ...grpc.CallOption) (*Ledger, error)
	Put(ctx context.Context, in *PutTransactionParams, opts ...grpc.CallOption) (*PutResult, error)
	Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Transaction, error)
}

type ordererClient struct {
	cc *grpc.ClientConn
}

func NewOrdererClient(cc *grpc.ClientConn) OrdererClient {
	return &ordererClient{cc}
}

func (c *ordererClient) CreateLedger(ctx context.Context, in *CreateLedgerParams, opts ...grpc.CallOption) (*Ledger, error) {
	out := new(Ledger)
	err := grpc.Invoke(ctx, "/proto.Orderer/CreateLedger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) GetLedger(ctx context.Context, in *GetLedgerParams, opts ...grpc.CallOption) (*Ledger, error) {
	out := new(Ledger)
	err := grpc.Invoke(ctx, "/proto.Orderer/GetLedger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) Put(ctx context.Context, in *PutTransactionParams, opts ...grpc.CallOption) (*PutResult, error) {
	out := new(PutResult)
	err := grpc.Invoke(ctx, "/proto.Orderer/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := grpc.Invoke(ctx, "/proto.Orderer/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Orderer service

type OrdererServer interface {
	CreateLedger(context.Context, *CreateLedgerParams) (*Ledger, error)
	GetLedger(context.Context, *GetLedgerParams) (*Ledger, error)
	Put(context.Context, *PutTransactionParams) (*PutResult, error)
	Get(context.Context, *GetParams) (*Transaction, error)
}

func RegisterOrdererServer(s *grpc.Server, srv OrdererServer) {
	s.RegisterService(&_Orderer_serviceDesc, srv)
}

func _Orderer_CreateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLedgerParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).CreateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/CreateLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).CreateLedger(ctx, req.(*CreateLedgerParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/GetLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).GetLedger(ctx, req.(*GetLedgerParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTransactionParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).Put(ctx, req.(*PutTransactionParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).Get(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Orderer",
	HandlerType: (*OrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLedger",
			Handler:    _Orderer_CreateLedger_Handler,
		},
		{
			MethodName: "GetLedger",
			Handler:    _Orderer_GetLedger_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Orderer_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Orderer_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0x49, 0x93, 0x6e, 0x4e, 0xb3, 0x6b, 0x19, 0x16, 0x89, 0xab, 0x48, 0x19, 0x44, 0x0a,
	0xc2, 0x5e, 0x54, 0x11, 0x6f, 0x75, 0x91, 0xba, 0x20, 0x5a, 0x82, 0x37, 0x5e, 0x4e, 0x93, 0x83,
	0x0d, 0x9b, 0x26, 0x65, 0x32, 0x29, 0x7a, 0xe3, 0x43, 0xf8, 0x12, 0x3e, 0x8b, 0xaf, 0xe0, 0x13,
	0xf8, 0x18, 0x32, 0x3f, 0x4d, 0x32, 0xb1, 0x7b, 0xb1, 0xe0, 0x55, 0xe7, 0x7c, 0xe7, 0xf4, 0xe4,
	0xfb, 0xbe, 0x39, 0x67, 0x20, 0xaa, 0x91, 0xef, 0x91, 0x5f, 0xee, 0x78, 0x25, 0x2a, 0xe2, 0xab,
	0x1f, 0xfa, 0x1d, 0xc8, 0x15, 0x47, 0x26, 0xf0, 0x3d, 0x66, 0x5f, 0x90, 0xaf, 0x18, 0x67, 0xdb,
	0x9a, 0x50, 0x88, 0xd2, 0x2a, 0xad, 0xaa, 0xf2, 0xaa, 0xca, 0xf0, 0x3a, 0x8b, 0x9d, 0x99, 0x33,
	0x0f, 0x13, 0x0b, 0x23, 0x04, 0x46, 0x25, 0xdb, 0x62, 0xec, 0xaa, 0x9c, 0x3a, 0x93, 0xfb, 0x10,
	0xec, 0x9a, 0x75, 0x91, 0xa7, 0xb1, 0x37, 0x73, 0xe6, 0x27, 0x89, 0x89, 0x48, 0x0c, 0xe3, 0x74,
	0xc3, 0xf2, 0x12, 0xb3, 0x78, 0xa4, 0x12, 0x87, 0x90, 0xfe, 0x70, 0xe0, 0x7c, 0xd5, 0x88, 0x4f,
	0x9c, 0x95, 0x35, 0x4b, 0x45, 0x5e, 0x95, 0x77, 0xa0, 0xf0, 0x18, 0xa0, 0x50, 0xb4, 0x3f, 0x74,
	0x44, 0x7a, 0x08, 0x79, 0x09, 0x91, 0xe8, 0x1a, 0xd7, 0xb1, 0x37, 0xf3, 0xe6, 0x93, 0x05, 0xd1,
	0x0e, 0x5c, 0xf6, 0xbe, 0x99, 0x58, 0x75, 0xf4, 0x1a, 0xee, 0x2d, 0x51, 0xfc, 0x0f, 0x47, 0xe8,
	0x67, 0x08, 0x97, 0x28, 0xee, 0xd0, 0x64, 0x0a, 0xde, 0x0d, 0x7e, 0x33, 0x3d, 0xe4, 0x51, 0x9a,
	0xaa, 0x35, 0x29, 0x53, 0xc3, 0xc4, 0x44, 0xf4, 0x8f, 0x03, 0x81, 0xe6, 0x28, 0x4b, 0xca, 0x66,
	0xbb, 0x46, 0xae, 0x5a, 0x7a, 0x89, 0x89, 0x24, 0xa3, 0x0d, 0xab, 0x37, 0x07, 0x46, 0xf2, 0x4c,
	0x9e, 0xc2, 0xd9, 0x8e, 0xe3, 0x5e, 0xff, 0xf3, 0x9d, 0xcc, 0xea, 0xb6, 0x03, 0x54, 0xd6, 0x95,
	0xf8, 0x55, 0xf4, 0xea, 0x46, 0xba, 0xce, 0x46, 0x5b, 0xd5, 0xfe, 0xd1, 0x39, 0x08, 0x6e, 0x9b,
	0x83, 0xb1, 0x35, 0x07, 0xe4, 0x11, 0x84, 0xa9, 0x9a, 0xc3, 0xec, 0xb5, 0x88, 0x4f, 0x94, 0x88,
	0x0e, 0xa0, 0x3f, 0x1d, 0x98, 0xf4, 0xae, 0xeb, 0x56, 0xbd, 0x9d, 0x55, 0x6e, 0xdf, 0x2a, 0x72,
	0x06, 0x6e, 0x9e, 0x19, 0x9d, 0x6e, 0xde, 0x9a, 0x3c, 0xea, 0x4c, 0x3e, 0x07, 0x7f, 0xcf, 0x8a,
	0xe6, 0x20, 0x43, 0x07, 0xad, 0x7f, 0x41, 0xcf, 0x3f, 0x8b, 0x69, 0x38, 0x64, 0xfa, 0x16, 0xc2,
	0x55, 0x23, 0x12, 0xac, 0x9b, 0x42, 0xc8, 0xa6, 0x2c, 0xcb, 0x50, 0x5f, 0xb4, 0x9f, 0xe8, 0x80,
	0x50, 0xf0, 0xd7, 0x45, 0x95, 0xde, 0x28, 0x8e, 0x93, 0x45, 0x64, 0xc6, 0xf1, 0x8d, 0xc4, 0x12,
	0x9d, 0xa2, 0xbf, 0x1c, 0xf0, 0x15, 0x60, 0xa8, 0x3b, 0x2d, 0xf5, 0x4e, 0xba, 0x6b, 0x49, 0x97,
	0xb4, 0xa4, 0x97, 0x6a, 0x15, 0xb4, 0xd2, 0x0e, 0x20, 0x4f, 0xe0, 0x54, 0x5e, 0xaf, 0x6a, 0xd9,
	0xbb, 0x4b, 0x1b, 0x6c, 0xe5, 0xfa, 0x3d, 0xb9, 0x74, 0xb0, 0x43, 0xd2, 0x8a, 0xc8, 0xde, 0x17,
	0xdb, 0x92, 0xf1, 0xc0, 0x92, 0xc5, 0x6f, 0x07, 0xc6, 0x1f, 0x79, 0x86, 0x1c, 0x39, 0x79, 0x05,
	0x51, 0xff, 0xb9, 0x21, 0x0f, 0x8c, 0xf8, 0x7f, 0xdf, 0xa0, 0x8b, 0x53, 0x93, 0x32, 0x95, 0x0b,
	0xb5, 0x48, 0x87, 0x79, 0x37, 0xb9, 0xc1, 0x96, 0x0e, 0xff, 0xf3, 0x02, 0xbc, 0x55, 0x23, 0xc8,
	0x43, 0x83, 0x1e, 0x7b, 0x67, 0x2e, 0xa6, 0x5d, 0xd2, 0xdc, 0xda, 0x33, 0xf0, 0x96, 0x28, 0xc8,
	0xb4, 0xfb, 0x86, 0x29, 0x3d, 0xf2, 0x70, 0xac, 0x03, 0x05, 0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x1d, 0xf5, 0x6e, 0x5d, 0x05, 0x00, 0x00,
}
