// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	CreateLedgerParams
	PutTransactionParams
	Ledger
	Transaction
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateLedgerParams struct {
	CocoonCodeId string `protobuf:"bytes,1,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Public       bool   `protobuf:"varint,3,opt,name=public" json:"public,omitempty"`
}

func (m *CreateLedgerParams) Reset()                    { *m = CreateLedgerParams{} }
func (m *CreateLedgerParams) String() string            { return proto1.CompactTextString(m) }
func (*CreateLedgerParams) ProtoMessage()               {}
func (*CreateLedgerParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateLedgerParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *CreateLedgerParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLedgerParams) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

type PutTransactionParams struct {
	Id           string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	CocoonCodeId string `protobuf:"bytes,2,opt,name=cocoonCodeId" json:"cocoonCodeId,omitempty"`
	LedgerName   string `protobuf:"bytes,3,opt,name=ledgerName" json:"ledgerName,omitempty"`
	Key          string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Value        []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutTransactionParams) Reset()                    { *m = PutTransactionParams{} }
func (m *PutTransactionParams) String() string            { return proto1.CompactTextString(m) }
func (*PutTransactionParams) ProtoMessage()               {}
func (*PutTransactionParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutTransactionParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutTransactionParams) GetCocoonCodeId() string {
	if m != nil {
		return m.CocoonCodeId
	}
	return ""
}

func (m *PutTransactionParams) GetLedgerName() string {
	if m != nil {
		return m.LedgerName
	}
	return ""
}

func (m *PutTransactionParams) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutTransactionParams) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Ledger struct {
	Number         int64  `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Hash           string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	PrevLedgerHash string `protobuf:"bytes,3,opt,name=prevLedgerHash" json:"prevLedgerHash,omitempty"`
	NextLedgerHash string `protobuf:"bytes,4,opt,name=nextLedgerHash" json:"nextLedgerHash,omitempty"`
	Name           string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Public         bool   `protobuf:"varint,6,opt,name=public" json:"public,omitempty"`
	CreatedAt      int64  `protobuf:"varint,7,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Ledger) Reset()                    { *m = Ledger{} }
func (m *Ledger) String() string            { return proto1.CompactTextString(m) }
func (*Ledger) ProtoMessage()               {}
func (*Ledger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ledger) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Ledger) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Ledger) GetPrevLedgerHash() string {
	if m != nil {
		return m.PrevLedgerHash
	}
	return ""
}

func (m *Ledger) GetNextLedgerHash() string {
	if m != nil {
		return m.NextLedgerHash
	}
	return ""
}

func (m *Ledger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ledger) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Ledger) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Transaction struct {
	Number     int64  `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Ledger     string `protobuf:"bytes,2,opt,name=ledger" json:"ledger,omitempty"`
	Id         string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Key        string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Value      string `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Hash       string `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	PrevTxHash string `protobuf:"bytes,7,opt,name=prevTxHash" json:"prevTxHash,omitempty"`
	NextTxHash string `protobuf:"bytes,8,opt,name=nextTxHash" json:"nextTxHash,omitempty"`
	CreatedAt  int64  `protobuf:"varint,9,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Transaction) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Transaction) GetLedger() string {
	if m != nil {
		return m.Ledger
	}
	return ""
}

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetPrevTxHash() string {
	if m != nil {
		return m.PrevTxHash
	}
	return ""
}

func (m *Transaction) GetNextTxHash() string {
	if m != nil {
		return m.NextTxHash
	}
	return ""
}

func (m *Transaction) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto1.RegisterType((*CreateLedgerParams)(nil), "proto.CreateLedgerParams")
	proto1.RegisterType((*PutTransactionParams)(nil), "proto.PutTransactionParams")
	proto1.RegisterType((*Ledger)(nil), "proto.Ledger")
	proto1.RegisterType((*Transaction)(nil), "proto.Transaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Orderer service

type OrdererClient interface {
	CreateLedger(ctx context.Context, in *CreateLedgerParams, opts ...grpc.CallOption) (*Ledger, error)
	Put(ctx context.Context, in *PutTransactionParams, opts ...grpc.CallOption) (*Transaction, error)
}

type ordererClient struct {
	cc *grpc.ClientConn
}

func NewOrdererClient(cc *grpc.ClientConn) OrdererClient {
	return &ordererClient{cc}
}

func (c *ordererClient) CreateLedger(ctx context.Context, in *CreateLedgerParams, opts ...grpc.CallOption) (*Ledger, error) {
	out := new(Ledger)
	err := grpc.Invoke(ctx, "/proto.Orderer/CreateLedger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordererClient) Put(ctx context.Context, in *PutTransactionParams, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := grpc.Invoke(ctx, "/proto.Orderer/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Orderer service

type OrdererServer interface {
	CreateLedger(context.Context, *CreateLedgerParams) (*Ledger, error)
	Put(context.Context, *PutTransactionParams) (*Transaction, error)
}

func RegisterOrdererServer(s *grpc.Server, srv OrdererServer) {
	s.RegisterService(&_Orderer_serviceDesc, srv)
}

func _Orderer_CreateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLedgerParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).CreateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/CreateLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).CreateLedger(ctx, req.(*CreateLedgerParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orderer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTransactionParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orderer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).Put(ctx, req.(*PutTransactionParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Orderer",
	HandlerType: (*OrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLedger",
			Handler:    _Orderer_CreateLedger_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Orderer_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xdb, 0x6a, 0xea, 0x50,
	0x10, 0x25, 0x89, 0x89, 0x66, 0x4e, 0x8e, 0x1c, 0x06, 0x91, 0x1c, 0xcf, 0x41, 0x24, 0x0f, 0xc5,
	0x27, 0x1f, 0x5a, 0x28, 0x7d, 0x2d, 0xbe, 0x54, 0x28, 0xad, 0x04, 0x7f, 0x60, 0x9b, 0x3d, 0xd4,
	0x50, 0x4d, 0x64, 0x27, 0x11, 0x4b, 0xff, 0xa2, 0x1f, 0xd6, 0xdf, 0xe8, 0x6f, 0x94, 0x7d, 0xa9,
	0xc6, 0x4b, 0xe9, 0x93, 0x7b, 0xd6, 0x1a, 0x33, 0x6b, 0xad, 0x19, 0x08, 0x0a, 0x12, 0x1b, 0x12,
	0xa3, 0xb5, 0xc8, 0xcb, 0x1c, 0x5d, 0xf5, 0x13, 0x71, 0xc0, 0xb1, 0x20, 0x56, 0xd2, 0x3d, 0xf1,
	0x27, 0x12, 0x53, 0x26, 0xd8, 0xaa, 0xc0, 0x08, 0x82, 0x24, 0x4f, 0xf2, 0x3c, 0x1b, 0xe7, 0x9c,
	0x26, 0x3c, 0xb4, 0x06, 0xd6, 0xd0, 0x8f, 0x0f, 0x30, 0x44, 0x68, 0x64, 0x6c, 0x45, 0xa1, 0xad,
	0x38, 0xf5, 0xc6, 0x2e, 0x78, 0xeb, 0x6a, 0xbe, 0x4c, 0x93, 0xd0, 0x19, 0x58, 0xc3, 0x56, 0x6c,
	0xaa, 0xe8, 0xcd, 0x82, 0xce, 0xb4, 0x2a, 0x67, 0x82, 0x65, 0x05, 0x4b, 0xca, 0x34, 0xcf, 0xcc,
	0xa0, 0x36, 0xd8, 0xbb, 0xcf, 0xdb, 0x13, 0x7e, 0x32, 0xd8, 0x3e, 0x33, 0xb8, 0x0f, 0xb0, 0x54,
	0x62, 0x1f, 0xe4, 0x78, 0x47, 0x75, 0xd4, 0x10, 0xfc, 0x03, 0xce, 0x33, 0xbd, 0x84, 0x0d, 0x45,
	0xc8, 0x27, 0x76, 0xc0, 0xdd, 0xb0, 0x65, 0x45, 0xa1, 0x3b, 0xb0, 0x86, 0x41, 0xac, 0x8b, 0xe8,
	0xdd, 0x02, 0x4f, 0xbb, 0x96, 0xba, 0xb3, 0x6a, 0x35, 0x27, 0xa1, 0xa4, 0x38, 0xb1, 0xa9, 0xa4,
	0xc7, 0x05, 0x2b, 0x16, 0x5f, 0x1e, 0xe5, 0x1b, 0x2f, 0xa0, 0xbd, 0x16, 0xb4, 0xd1, 0xff, 0xbc,
	0x93, 0xac, 0x96, 0x70, 0x84, 0xca, 0xbe, 0x8c, 0xb6, 0x65, 0xad, 0x4f, 0x2b, 0x3a, 0x42, 0x77,
	0x39, 0xba, 0x67, 0x73, 0xf4, 0xea, 0x39, 0xe2, 0x7f, 0xf0, 0x13, 0xb5, 0x2d, 0x7e, 0x5b, 0x86,
	0x4d, 0x25, 0x75, 0x0f, 0x44, 0x1f, 0x16, 0xfc, 0xaa, 0x45, 0xfc, 0xad, 0xab, 0x2e, 0x78, 0x3a,
	0x2e, 0xe3, 0xcb, 0x54, 0x72, 0x19, 0x29, 0x37, 0x6e, 0xec, 0x94, 0xff, 0x14, 0xa4, 0x6f, 0x82,
	0xdc, 0xa5, 0xe4, 0xd5, 0x52, 0xea, 0x03, 0xc8, 0x3c, 0x66, 0x5b, 0xe5, 0xbc, 0xa9, 0x97, 0xb4,
	0x47, 0x24, 0x2f, 0x73, 0x30, 0x7c, 0x4b, 0xf3, 0x7b, 0xe4, 0xd0, 0xa9, 0x7f, 0xe4, 0xf4, 0xf2,
	0x15, 0x9a, 0x8f, 0x82, 0x93, 0x20, 0x81, 0x37, 0x10, 0xd4, 0x0f, 0x18, 0xff, 0xea, 0xfb, 0x1e,
	0x9d, 0x5e, 0x75, 0xef, 0xb7, 0xa1, 0x4c, 0xe7, 0x35, 0x38, 0xd3, 0xaa, 0xc4, 0x7f, 0x06, 0x3d,
	0x77, 0x9f, 0x3d, 0x34, 0x64, 0x8d, 0x99, 0x7b, 0x0a, 0xba, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xfc, 0x99, 0x8d, 0xde, 0x50, 0x03, 0x00, 0x00,
}
